SaitoTech/saito-rust

- src/keypair.rs
Removed `expect()` where:
- error is not critical
- when error message does not have any meaning
> Get rid of panics

- .gitignore
- Cargo.lock
- Cargo.toml
- src/keypair.rs
- src/lib.rs
- Cleaned up rand usage by removing `OsRng` and using `thread_rng()`
- Replace `lazy_static` with singleton struct `SECP256K1`
- Removed unnecessary dependencies (we can add it later when needed)
- Add public key to the keypair
- Change some method names to be more compliant with Rust naming convention (ie `new_from_str() => from_str()`). It will look more consistent as other packages we use already uses such method names.
> Cleanup keypair generation

- src/block.rs
- src/crypto.rs
- src/transaction.rs
- Changed few functions to return reference of the object without cloning as I believe most use cases will be read-only. Cloning can be done if necessary after the function call.
- Optimize and simplify `set_transactions()` function to use no memcpy whereas [`std::mem::swap` uses temporary buffer to do the swapping](https://doc.rust-lang.org/src/core/ptr/mod.rs.html#518). It is indeed a useful function if we need the old transactions in `self.body.txs` but we don't. So it's safe to assign the new transactions. It should do the same thing as previous function and the tests pass. But currently, test for `set_transactions()` is too shallow and I don't actually get the logic behind setting `current_sid`.
> Optimize set_transactions().

- src/blockchain.rs
- src/lib.rs
- src/shashmap.rs
Minor change -- shashmap should be a generic key=>value data structure as opposed to a class to one use-case. We can instantiate it in ways that make it clear what the shashmap is being used to manage:
let utxoset = Shashmap::new();
The storage class Stephen is putting together will basically need to support saving blocks to disk and managing the UTXO set in this routing client (i.e. no need to database support) so it shouldn't be a problem to use it as the API contact point for updates to the UTXO set.
Need another reason? Hannes suggested I update my user.email and I'm admittedly curious if it makes a different in how this appears. So welcome back, Shashmap. It has been too long!
> return of the shashmap

- src/block.rs
- src/blockchain.rs
- src/lib.rs
- src/longest_chain_queue.rs
- src/main.rs
There was a panic caused by trying to add blocks beyond 2x epoch length because we were using block id 0 for all blocks and at some point block 0 would fall out of the longest_chain_queue. This change requires the block id to be the parent's id + 1 and adjusts the tests to comply with this. I also discovered a good test which can be seen in the last lines of blockchain.rs's tests that demo's a problem that will exist until we begin cleaning up old un-confirmed blocks from fork_tree.
> Block id for mock blocks

- src/block.rs
- src/blockchain.rs
- src/burnfee.rs
- src/consensus.rs
- src/golden_ticket.rs
- src/lib.rs
- src/main.rs
- src/mempool.rs
- src/storage.rs
- src/transaction.rs
- src/utxoset.rs
Apologies for the massive PR, but this was split off from our `add_block` work and deserved a seperate PR.
In this PR, we
- Change `Block` to contain `difficulty` and `start_burnfee` inside `BlockCore` instead of at the high level
- Simplify how BurnFee operates, reintroduce `start_burnfee` for validation purposes
- Introduce different transaction validation for `Normal` and `GoldenTicket` transactions
- Simplify how `consensus` is running
> Burnfee and Block Validation Refactor

- .gitignore
- src/blockchain.rs
- src/consensus.rs
- src/golden_ticket.rs
- src/lib.rs
It is proving very difficult to use a thread_local blockchain object which also allows async functions.
We don't want to restrict ourselves to only writing non-async functions because this will only get harder and harder to fix as we move forward.
thread_local's .with(|| {...} ) requires a closure. Async closures are unstable in rust. It may be possible to enable async closure or to use an FnOnce function instead of a closure, but this is tricky to get working, is holding us back, and can probably be classified as premature optimization.
If we instead simply use a lazy_static for getting global reference to the blockchain object, this isn't a problem. It may even end up being faster, although this depends on how much tokio benefits from having access to multiple threads vs how much cost …
> feat: use global arc<mutex<blockchain>> for shared state

- Cargo.toml
Without a default bin this happens:  
```bash
cargo run
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: saito-spammer, saito_rust
```
Renaming `saito-spammer` to `saito_spammer` because of the `saito_rust` naming
> chore: set default bin for rust

- src/consensus.rs
- src/crypto.rs
- src/lib.rs
- src/wallet.rs
This creates a generic wallet that works exactly like the mempool.
- private channel for in-wallet messages
- ability to listen on and public system-wide broadcasts
This pushes the Keypair INTO the crypto-class as part of our efforts to contain anything that touches algorithm-specific code to that class. The wallet has a copy, but gets_ the standard bytes-array data. We may want to think about not storing the Keypair in the wallet at all.
> wallet class and keypair in crypto class

- src/mempool.rs
- src/transaction.rs
My last changes didn't respect `Mempool` as a block queue well enough. I have no issue with this, but if we're going to have a block queue, it's best that we're consistent with a queue operations.
This means
- `Mempool` uses `VecDeque` as a queue. It has the ability to add unique blocks and process them FIFO.
- Blocks are added to the block queue, then added to the chain sequentially via a `ProcessBlocks` message.
- To adhere to a FIFO queue, there should be no function that attempts to prioritize blocks over others via `take_block`. We simply process the queue each time we wish to add a block to the chain.
There are still some questions to be answered
- How do different parts of the program add blocks into the queue? For now, my assumption is that we're passing the mempool reference, …
> Refactor: Orienting Mempool operations around block queue with consistency

- src/big_array.rs
- src/block.rs
- src/lib.rs
- src/slip.rs
- src/transaction.rs
Fixed build by implementing de/serialize for big arrays.
`#[serde_as(as = "[_; 33]")]` does not work when the array size is larger than 32 so we have to manually implement it.
> fix: de/serialize big arrays

- Cargo.lock
- Cargo.toml
- src/block.rs
- src/blockchain.rs
- src/crypto.rs
- src/mempool.rs
- src/slip.rs
- src/transaction.rs
These numbers speak for themselves:
Orders of magnitude increase in speed without any major differences in security in comparison to sha2.
Additionally, blake3 allows us to hash in parallel. Based on their own benchmarks, inputs over 128 kb show improvements in speed when parallelized. This would be excellent in speeding up signature creation/verification for `Transaction`s
> Feature: use blake3 for hashing algorithm with parallel hashing

- src/consensus.rs
- src/crypto.rs
- src/mempool.rs
- src/transaction.rs
- src/wallet.rs
A few thoughts:
- Wallet can be passed as a local attribute for both `Mempool`, `Blockchain` and other parts of the program
- It does not need a `run` function, all write operations can be done within `Blockchain`
- Access to `privatekey` should be hidden within `Keypair` inside `Wallet`. It's a security concern to pass around a node's private key all over the program
- Therefore, `sign` should be moved out of crypto and strictly into `Wallet`. The access problem is solved by passing `Wallet` as a reference widely to parts of the program that need it
> Refactor: demoted Wallet with limited access to private key 

- src/block.rs
- src/blockchain.rs
- src/blockring.rs
- src/consensus.rs
- src/crypto.rs
- src/lib.rs
- src/mempool.rs
- src/slip.rs
- src/transaction.rs
- src/wallet.rs
Will be continuing to work on this, but sharing a push so that people can see this code in advance. This brings the essentials of wind / unwind chain into Rust. It updates the Blockchain file so that blocks are processed and added in a chain. And it preserves but modifies the fast-access VecDeque that Clay has suggested as a BlockRing.
Blockring.rs is an abstract class and the exact data structures inside should be discussed and can be upgraded without affecting the logic of how we process blocks. The need for the elements in the Blockring to have variable-size components means we can no longer store this on the stack in contiguous memory, so I am wondering if the best approach might be using a SliceDeqVeque -- https://docs.rs/slice-deque/0.3.0/slice_deque/. We could also use a Vector and …
> Sequential refactor blockring and blockchain add block

- src/block.rs
- src/blockchain.rs
- src/lib.rs
- src/mempool.rs
- src/merkle.rs
- src/transaction.rs
This branch manually generates MerkleRoot instead of relying on an external library. Among the advantages:
* this uses the default Saito hashing algorithm instead of using Sha256
* rayon used for parallel generation of hashes, etc.
Timestamps below calculated on blocks with 10,000 txs each of which has a 1024 byte message field.
OLD
... start merkle: 1625035550570
... stop merkle:  1625035550714
NEW
... start merkle: 1625035717373
... stop merkle:  1625035717389
> parallel merkle root generation

- src/blockchain.rs
- src/blockring.rs
- src/transaction.rs
It's important that we keep the code warning-free. Warning are useful when developing because I use them to catch my own mistakes. This doesn't work well if there are other warnings already present.
> chore: cleanup warnings

- .github/workflows/rust.yml
This will make sure we always use the latest version of Rust for the build-step in Github actions.  
Currently with this build works, but tests fail, like it does locally.
> chore: update to latest rust version in GH action

- src/block.rs
- src/blockchain.rs
- src/hop.rs
- src/lib.rs
- src/mempool.rs
- src/slip.rs
- src/transaction.rs
- src/wallet.rs
This is a decent stopping point for a merge. Some of the features implemented in this push are needed for testing and development. Others constitute core functionality. Here are the changes.
We are flushing actual SAITO into the network through the creation of VIP transactions in block #1 -- these are created manually in block.add_block() by invoking a special function in transactions. For now the block validation code will permit these transactions to slip through as OK.
The wallet is saving the slips when a block is added to the end of the longest chain. This is not robust code and we intend to remove it -- it adds everything, not just the transactions for itself. The point is to be able to generate valid spendable slips from the mempool during the next loop of block creation. This …
> Sequential refactor txs spend tokens if possible

- src/bin/spammer.rs
- src/block.rs
- src/mempool.rs
- src/network.rs
- src/slip.rs
- src/transaction.rs
Includes some initial support for automatic transaction rebroadcasting.
We are not adding the ATR transactions to the block or validating them. But we are calculating them based on the assumption of a 2 block EPOCH. So this is scaffold code. What remains is basically to decide how to store the ATR transactions in the block so that we can have a fast and optimized sweep through the transaction set.
This PR also includes some updates to the spammer code that gets the transactions it is producing using Saito tokens owned by the wallet. And adds routing hops to them on receipt in the mempool so that we can calculate / test the routing work-related functions as needed.
I think this is ready for merge. The critical parts are largely contained to the Block.rs function that generates consensus …
> Initial Support : Automatic Transaction Rebroadcasting

- src/block.rs
- src/mempool.rs
- src/transaction.rs
This push adds payments for routing nodes and mining nodes.
The fee-bearing transaction is generated and attached to the {cv} object.
It is pushed directly into the transactions vector on block creation.
And it is hashed and checked against the in-block fee transaction during validation.
> Router and Miner Payouts

- TODO.txt
- src/bin/spammer.rs
- src/block.rs
- src/blockchain.rs
- src/hop.rs
- src/mempool.rs
- src/slip.rs
- src/transaction.rs
A lot of confusing function names have been replaced with the GENERATE_METADATA class of functions. All functions with this name or prefix handle the preparation of data needed to produce or validate blocks, i.e.:
block.generate_metadata()
transaction.generate_metadata()
transaction.generate_metadata_hashes()
transaction.generate_metadata_fees_and_slips()
etc. 
The serialization / deserialization code has been updated for transactions (and blocks) so that we include routing paths (self.path). An additional class serialize_for_net_with_hop(hop : Hop) can be used to serialize with the additional hop of the node to which we are sending the transaction -- if this approach works we can do something similar with block.
ATR transaction creation and validation code is more fleshed out, although …
> Sequential refactor generate metadata refactor

- Cargo.lock
- Cargo.toml
- src/block.rs
- src/blockchain.rs
- src/blockring.rs
- src/mempool.rs
- src/slip.rs
- src/storage.rs
- src/transaction.rs
- src/wallet.rs
Some significant changes:
wind and unwind chain are now ASYNC.
we do this so that we can potentially load blocks from disk instead of just fetching from the blockchain.blocks index when re-writing the chain.
minor fix to the way slip validation is handled
ATR improved, with the GENESIS_PERIOD now managed explicitly by blockchain.
> Sequential refactor wind chain async block load

- src/bin/spammer.rs
- src/block.rs
- src/blockchain.rs
- src/consensus.rs
- src/mempool.rs
- src/networking/network.rs
- src/storage.rs
- src/test_utilities/mocks.rs
- src/time.rs
- src/transaction.rs
- src/wallet.rs
This does some minor refactoring to mempool to provide testable interfaces(moved some code into try_bundle_block and process_blocks functions). 
This also removes GenerateBlock, which seems to be a duplicate of TryBundleBlock.
This also adds a Trait TimestampGenerator which has a default impl which simply wraps the system timestamp(create_timestamp). use SystemTimestampGenerator to access this. It also adds a separate implementation of the trait called MockTimestampGenerator which can be used in test to pause/advance the timestamp. The idea is for this to be used in place nearly everywhere that we currently use create_timestamp(). This makes testing things like mempool and block validation much simpler.
This also adds some basic mempool tests which still need work. This was done to test …
> Mempool testing

- src/networking/network.rs
Spent a lot of time trying to figure out how to do a graceful shutdown with tokio. Finally realized that simply replacing the time package with the tokio one will at least let tokio shutdown the tasks that have been launched via tokio::select.
> fix: allow tokio::select to shutdown network

- src/bin/saitocli.rs
- src/bin/spammer.rs
- src/block.rs
- src/blockchain.rs
- src/blockring.rs
- src/consensus.rs
- src/crypto.rs
- src/mempool.rs
- src/networking/network.rs
- src/slip.rs
- src/staking.rs
- src/test_utilities/mocks.rs
- src/transaction.rs
- src/wallet.rs
This reverts the Wallet constructor to avoid needing a wallet file and password. Instead of providing the wallet file as part of the constructor, the software will auto-generate on start and optionally call wallet.load_keys(file, pswd) to load content that exists in the provided walletfile. There are several reasons why the reversion is preferred:
* less clutter - Wallet::new()
* consistency - other classes use new() by convention
* simpler tests - most do not need a pre-generated wallet or are better with a random keypair.
* less dependence on external files - minimize potential for errors
* extensible - load_ functions are the proper place for code to load data
* saving & loading - should be parallel functions which can be called anytime, not just at init
All files and tests have been …
> fix: tests working with reverted wallet constructor

- src/bin/spammer.rs
- src/blockchain.rs
- src/consensus.rs
- src/main.rs
- src/mempool.rs
- src/networking/handlers.rs
- src/networking/network.rs
- src/networking/peer.rs
- src/test_utilities/mocks.rs
This push contains some architectural simplifications and code changes. These changes do not aim to change functionality. They are focused on simplifying the codebase, removing structs that are not being used, and ensuring that different files and classes follow the same organizational logic. Comments have also been added and removed where necessary to provide a better onboarding experience for new developers.
Specific changes include:
CONSENSUS:
* removal of unused SaitoMessages
* more intuitive file-organization
* improved consistency in variable initialization (RwLock)
MEMPOOL:
* removal of AddBlockAccepted / AddTransactionAccepted
* simpler and clearer names for LOCAL broadcast channel events
* simplification of function names and improved naming consistency
NETWORK:
* implementation …
> Architectural simplifications and corner sanding

- src/networking/network.rs
warp server startup working with network_lock.
the network is never transfered into a thread or seized in runtime. the server still starts on a separate thread.
> fix: network is initializing and running

- src/slip.rs
- src/transaction.rs
These were needed when we only had Normal and Other types because TryFromByte required at least 2 fields in the enum. They are no longer needed.
> fix: Other removed from TryFromByte enums

- .gitignore
- src/networking/mod.rs
- src/networking/network.rs
- src/networking/signals.rs
The warp port does not shutdown properly when we issue interrupt signal to the binary. Therefore, I used [this warp function](https://docs.rs/warp/0.3.1/warp/struct.Server.html#method.bind_with_graceful_shutdown) for graceful shutdown feature.
> feat: graceful shutdown warp

- src/blockchain.rs
- src/consensus.rs
- src/mempool.rs
- src/networking/network.rs
- src/networking/peer.rs
To try this, from one repo do: cargo run -- --spammer
This should give you blocks and Warp should start listening for socket connections.
if you want to start over, do: rm data/blocks/*.sai
From another repo, do: cargo run -- --config=config2.yml --password=asdf
This will try to connect to the peer specified in config2.yml(which is the default port which we ran above with cargo run).
The 2nd node should connect and sync itself with the first node, then when the first node makes a block, we want the NetworkNewBlock message to trigger a SNDBLKHD API message and to 2nd node which should then do a REQBLOCK back to the first node.
> feat: blockchain signal network to propagate blocks.

- src/crypto.rs
Now, the block verification will cause panic when the block creator field is ill-formed. Such block can cause all recipient clients to panic so I believe it is a critical fix.
- safer handling of ill-formed fields on verification.
> fix: no panic on verify()

- Cargo.toml
Rust language is not fully mature yet, we should keep growing along with its ecosystem. 
The upgrade only helps us benefit more from the language's support community, some fixes have also been applied in the new version. 
Follow this [guide](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html)
Re-built & all tested passed.
> feat: upgrade to latest Rust edition

- src/block.rs
Refactor `Block` type for safer getters/setters.
- change hash values to `Option<SaitoHash>` for safer memoization 
- all setters that affect the `hash` or `pre_hash` now sets the memoized hash values to `None` to make sure that outdated hash values are not used.
- `generate_hash()`, `generate_pre_hash()` will re-hash if necessary to update the memoized hash values.
- `get_hash()`, `get_pre_hash()` will try to read memoized value and will recalculate if not available (but will not update because we don't want to get mutable reference in getters. Use `generate` functions to update the hash values).
> Refactor block type
