src/block.rs
src/transaction.rs

Cleanup of existing structs and functions based on conversations taken place over the last few PRs.
Gonna need to keep working on have a clean commit history @escapedcat. Will squash and merge to try and minimize the damage.

Refactor: rename attributes and remove unnecessary public access

---

src/block.rs
src/blockchain.rs
src/lib.rs

Just the basics so that we can merge with `Mempool` #30 under some sort of runtime to be determine in #29.

Blockchain Implementation

---

src/blockchain.rs
src/consensus.rs
src/mempool.rs
src/utxoset.rs

This is the first pass through adding `UTXOSet` to `Blockchain` to start to add `Slips` for validation purposes.

Feature: add utxoset to blockchain first implementation with minor refactoring

---

src/block.rs
src/blockchain.rs
src/burnfee.rs
src/consensus.rs
src/golden_ticket.rs
src/lib.rs
src/main.rs
src/mempool.rs
src/storage.rs
src/transaction.rs
src/types.rs
src/utxoset.rs

First implementation of memory management surrounding `Blockchain`. We want this structure to be accessed in multiple places in the program, and utilizing `thread_local` seems to be a good start to achieve this.
A big thing to keep in mind is that this current version doesn't have very good support for `async` functions, which poses a bit of a problem for the future of `add_block`.

Memory management of Blockchain with thread_local!

---

src/longest_chain_queue.rs

longest chain tests accidentally got removed and started to go stale. I've put them back and fixed.

repair longest chain tests

---

.github/workflows/rust.yml

Github needs the proper test config

fix: github tests need proper configuration

---

README.md

docs: add install rust info

---

README.md

For the OSX people who haven't installed it yet

docs: add xcode info

---

src/block.rs
src/consensus.rs
src/crypto.rs
src/forktree.rs
src/golden_ticket.rs
src/keypair.rs
src/longest_chain_queue.rs
src/mempool.rs
src/slip.rs
src/transaction.rs

Just adding some additional tests and clean up some functions and comments.

Refactor: remove extraneous code and update tests

---

src/blockchain.rs
src/utxoset.rs

Increased the test coverage of utxoset.

Utxoset coverage

---

src/bin/spammer.rs
src/blockchain.rs
src/consensus.rs
src/lib.rs
src/mempool.rs
src/network.rs

@trevelyan brought up some valid concerns with the initial structuring of our channels and how they operate. This is my proposal for how we can mix global broadcast channels with internal channels.

Refactor: mix global broadcast channels with internal channels

---

src/block.rs
src/blockchain.rs
src/blockring.rs
src/mempool.rs
src/wallet.rs

Just a little bit of cleanup from clippy warnings and trying to get some more tests in. Once we start solidifying other parts of the code, more tests will follow.

Chore: cleanup for clippy warnings and mempool testing

---

Cargo.lock
Cargo.toml
src/block.rs
src/blockchain.rs
src/blockring.rs
src/crypto.rs
src/mempool.rs
src/slip.rs
src/transaction.rs

Still might need some polish about where and when we're generating and validating the merkle root, but we have the foundation here to iterate on it

Feature: merkle root generation with verification

---

src/block.rs
src/blockchain.rs
src/burnfee.rs
src/lib.rs
src/mempool.rs

BurnFee updated to be a u64, measuring the total amount of NOLAN required to produce a block.
Help avoids tail-end errors in floating-point arithmetic causing consensus-forking behaviors.

Sequential refactor burn fee inclusion

---

src/block.rs
src/blockchain.rs
src/consensus.rs
src/mempool.rs
src/slip.rs
src/storage.rs
src/test_utilities/mocks.rs
src/wallet.rs

Mixture of Stephen's updated with a new WalletSlip component that does not cross the streams with the slips in txs.

Sequential refactor wallet update

---

src/block.rs
src/blockchain.rs
src/crypto.rs
src/mempool.rs
src/slip.rs
src/transaction.rs
src/wallet.rs

Various updates primarily to block creation in mempool to make benchmarking and review easier.
Easier output for benchmarking times etc.

Sequential refactor block creation into block

---

src/blockchain.rs
src/slip.rs
src/test_utilities/mocks.rs

I tried making a fork using the new generate_block method. I still can't get add_block to accept a fork.

test: repair add_fork_test

---

src/blockchain.rs
src/transaction.rs

I believe this fixes the problems with wind/unwind chain. Would appreciate a review -- this and the add_block() function in blockchain are where we ran into the hardest problems in the javascript version. i hope that a lot of that was from the messiness of the code and that this implementation will be easier because it is cleaner.
In terms of the problems fixed, I think the conceptual messiness responsible for them originally was my use of the term current_wind_index/current_unwind_index in a way that suggested that the variable tracked BOTH [# of block in block_id sequence] as well as [index position in new_chain/old_chain vector].
I don't know if there is a better way to name those variables, but I have tried to comment-the-fuck out of the code so that it is always clear with specific …

Review of wind unwind

---

src/block.rs
src/blockchain.rs
src/mempool.rs
src/network.rs
src/slip.rs
src/transaction.rs
src/wallet.rs

We look to separate the metadata generation logic and the validation logic in this PR, along with some cleanup to the validation functions themselves

Validation refactor and cleanup

---

src/block.rs
src/blockchain.rs
src/blockring.rs
src/hop.rs
src/miner.rs
src/transaction.rs

This also has a new test in blockchain.rs that handles a 4 block add_block() process.
We can build off this to build more complicated multi-block fork tests.

Work in Process -- ATR and Fee Transaction Generation

---

src/block.rs
src/blockchain.rs
src/burnfee.rs
src/consensus.rs
src/mempool.rs
src/networking/handlers.rs
src/slip.rs
src/staking.rs
src/test_utilities/mocks.rs
src/time.rs
src/transaction.rs
src/wallet.rs

This adds additional testing to the staking class and code, along with the ability to create transactions that will withdraw tokens. Validation of those transactions is handled.
This also adds the code to check the last_shared_ancestor given a fork_id and a block_id.

Sequential refactor staking polish

---

src/block.rs
src/blockchain.rs
src/blockring.rs
src/mempool.rs
src/staking.rs
src/test_utilities/mocks.rs
src/test_utilities/mod.rs
src/test_utilities/test_manager.rs
src/transaction.rs
src/wallet.rs

TestManager in test_utility folder simplifies chain re-org tests and includes some checks on the consistency of the UTXOSet.

Sequential refactor test manager

---

src/block.rs
src/blockchain.rs
src/blockring.rs
src/mempool.rs
src/staking.rs
src/storage.rs
src/test_utilities/mocks.rs
src/test_utilities/mod.rs
src/test_utilities/test_manager.rs
src/transaction.rs

Merges Stephen's fixes to the block-saving process with the intermediary staking update I have been working on.
This prints output information on stakers to the screen when producing blocks, but should not break consensus.

Sequential refactor staking depth

---

src/block.rs
src/blockchain.rs
src/blockring.rs
src/mempool.rs
src/merkle.rs
src/networking/api_message.rs
src/slip.rs
src/staking.rs
src/time.rs
src/transaction.rs
src/wallet.rs

Trying to reduce the amoutn of clippy warnings step by step. Please have a look. Thanks!

style: remove some clippy warnings

---

src/block.rs
src/mempool.rs

quick addition of mempool test requested by Clay.
pushing quickly into main as was in this branch when I made hte fix.

fix: tests for mempool block production

---

src/block.rs
src/blockchain.rs
src/blockring.rs
src/mempool.rs
src/wallet.rs

We used to have the wallet update itself after a block was successfully added.
This PR moves this so that it takes place during the wind / unwind process in parallel to the other data structures:
- blockring
- staking tables
- utxoset

Wallet update to on chain reorganization

---

src/block.rs
src/blockchain.rs
src/staking.rs
src/test_utilities/test_manager.rs

Blockchain validates that 2 out of 6 (configurable) most recent blocks include golden tickets. If this condition does not hold, the block will be deemed invalid according to consensus criteria.

fix: Eliminate Mining-Free Chains

---

src/block.rs
src/staking.rs
src/transaction.rs

This is just a merge of Clay's main with my main.
I had thought there was more work required, so created a branch to handle it.
Turns out Clay already did the grunt work on this. will push and merge what are mostly println cleanup.
thx C

Merge clay networking code

---

src/block.rs
src/blockchain.rs
src/mempool.rs
src/networking/peer.rs
src/slip.rs
src/staking.rs
src/test_utilities/test_manager.rs
src/transaction.rs
src/wallet.rs

Merging a few days of work into revised main

Merging latest staker fixes pr

---

src/block.rs
src/blockchain.rs
src/mempool.rs
src/networking/peer.rs
src/slip.rs
src/staking.rs
src/test_utilities/test_manager.rs
src/transaction.rs
src/wallet.rs

Table / Vector of stakers is now maintained in order so that the order of entry / addition (i.e. winding / unwinding) does not affect which participant is selected by any particular random number.
Comes with improved and expanded test cover.
Also removes an unnecessary / outdated function from the staker.rs class.

Staker deposits and testing

---

README.md

As commented in #270 
I figured opening the PR would be faster than waiting for anyone to answer my question, so here you go 😄

docs: remove outdated spammer paragraphs

---

src/blockchain.rs
src/storage.rs
src/test_utilities/test_manager.rs

added some tests to find the bug

bugfix: loading blocks of another chain from disk

---

src/block.rs

Remove obsolete struct to simplify the code base.

refactor: Remove obsolete RouterPayout struct

---

src/blockchain.rs

Update and match the Onchain Reorganization behavior in Saito-Rust with Saito-lite-rust #328

Feature: on chain reorganization update
